import type { Screenshot } from "@/types/screenshot";

export const quickFilters = [
  "Code",
  "Design",
  "Errors",
  "Documents",
  "Receipts",
  "Ideas",
  "AI",
  "UI Inspiration",
] as const;

export const mockScreenshots: Screenshot[] = [
  {
    id: "1",
    title: "Next.js Authentication Error",
    imageUrl: "",
    category: "Errors",
    tags: ["React", "Supabase", "Error"],
    createdAt: "2026-08-04",
    aspectRatio: 1.4,
  },
  {
    id: "2",
    title: "Dark Pricing Page — Linear",
    imageUrl: "",
    category: "UI Inspiration",
    tags: ["Pricing", "Dark UI"],
    createdAt: "2026-08-04",
    aspectRatio: 0.75,
  },
  {
    id: "3",
    title: "Tailwind Navbar Animation",
    imageUrl: "",
    category: "Code",
    tags: ["Tailwind", "Framer Motion"],
    createdAt: "2026-08-03",
    aspectRatio: 1.1,
  },
  {
    id: "4",
    title: "Invoice from Amazon Web Services",
    imageUrl: "",
    category: "Receipts",
    tags: ["AWS", "Invoice"],
    createdAt: "2026-08-03",
    aspectRatio: 1.3,
  },
  {
    id: "5",
    title: "Claude Prompt for Data Extraction",
    imageUrl: "",
    category: "AI",
    tags: ["Claude", "Prompt"],
    createdAt: "2026-08-02",
    aspectRatio: 0.9,
  },
  {
    id: "6",
    title: "MongoDB Connection Timeout",
    imageUrl: "",
    category: "Errors",
    tags: ["MongoDB", "Node.js"],
    createdAt: "2026-08-02",
    aspectRatio: 1.2,
  },
  {
    id: "7",
    title: "Login Page — Arc Browser Style",
    imageUrl: "",
    category: "UI Inspiration",
    tags: ["Login", "Glassmorphism"],
    createdAt: "2026-08-01",
    aspectRatio: 0.7,
  },
  {
    id: "8",
    title: "Figma Component Structure",
    imageUrl: "",
    category: "Design",
    tags: ["Figma", "Design System"],
    createdAt: "2026-08-01",
    aspectRatio: 1.05,
  },
  {
    id: "9",
    title: "Q3 Product Roadmap Notes",
    imageUrl: "",
    category: "Ideas",
    tags: ["Planning", "Notion"],
    createdAt: "2026-07-31",
    aspectRatio: 1.15,
  },
  {
    id: "10",
    title: "GitHub Repository — screenshot-ai",
    imageUrl: "",
    category: "Code",
    tags: ["GitHub", "TypeScript"],
    createdAt: "2026-07-30",
    aspectRatio: 0.85,
  },
  {
    id: "11",
    title: "Starbucks Receipt",
    imageUrl: "",
    category: "Receipts",
    tags: ["Receipt"],
    createdAt: "2026-07-30",
    aspectRatio: 1.5,
  },
  {
    id: "12",
    title: "Blue Analytics Dashboard",
    imageUrl: "",
    category: "UI Inspiration",
    tags: ["Dashboard", "Charts"],
    createdAt: "2026-07-29",
    aspectRatio: 1.0,
  },
];
